backend:
  name: git-gateway
  branch: main # Cambia esto por la rama que estás usando

media_folder: "assets/images" # Ruta donde se guardan las imágenes
public_folder: "/images" # Ruta pública de las imágenes

collections:
  - name: "posts" # Nombre de la colección
    label: "Posts" # Etiqueta que se mostrará en el CMS
    folder: "src/content/posts" # Carpeta donde se guardan los archivos
    create: true # Permite crear nuevos posts
    slug: "{{slug}}" # Definición de slug
    fields: # Campos del formulario
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "tags", label: "Tags", widget: "list", field: { name: "tag", widget: "string" } }
      - { label: 'Categoría', name: 'category', widget: 'select', options: ['Sostenibilidad', 'Viajes', 'Conciertos', 'Rondas', 'Fiestas', 'Discos', 'Despedidas', 'Bodas', 'En la plaza'] }
      - { name: "excerpt", label: "Excerpt", widget: "text" }
      - { name: "body", label: "Body", widget: "markdown" }
